"""Script generator for executable Python/OpenServer scripts.

License Optimization Strategy:
- Only ONE instance of PROSPER open at a time
- Only ONE instance of MBAL open at a time
- GAP can be open simultaneously (it orchestrates)
- Batch operations (IPR/VLP generation) process wells sequentially:
  Open PROSPER → process well → save → close PROSPER → next well
- MBAL models are opened one at a time and saved before closing
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from petex_mcp.models.commands import OpenServerCommand


class ScriptGenerator:
    """Generates executable Python/OpenServer scripts for model-building operations.
    
    License optimization: Scripts are structured so that only 1 PROSPER 
    and 1 MBAL instance are active at any time. Batch well operations 
    process sequentially (open → work → save → close → next).
    """

    def generate(
        self,
        operation: str,
        commands: list[OpenServerCommand],
        description: Optional[str] = None,
    ) -> str:
        """Generate a complete, self-contained Python script for the operation.
        
        License optimization: Automatically ensures any PROSPER/MBAL opened 
        is shut down at the end of the script. Prevents orphan instances.
        """
        # Auto-inject SHUTDOWN for any app that was opened but not closed
        commands = self._ensure_license_lifecycle(commands)

        lines: list[str] = []

        # Docstring header
        lines.append(f'"""PETEX OpenServer Script: {operation}')
        lines.append("")
        lines.append(f"Generated by PETEX MCP Server")
        lines.append(f"Timestamp: {datetime.now(timezone.utc).isoformat()}")
        lines.append("")
        lines.append("License optimization: max 1 PROSPER + 1 MBAL instance at a time.")
        lines.append('"""')
        lines.append("")
        lines.append("from openserver import OpenServer")
        lines.append("import time")
        lines.append("")
        lines.append("with OpenServer() as c:")

        if description:
            lines.append(f"    # {description}")
            lines.append("")

        if not commands:
            lines.append("    pass")
        else:
            for cmd in commands:
                lines.append(f"    {self._build_command_line(cmd)}")

        lines.append("")
        return "\n".join(lines) + "\n"

    def _ensure_license_lifecycle(
        self, commands: list[OpenServerCommand]
    ) -> list[OpenServerCommand]:
        """Ensure every opened PETEX app is properly started and shut down.
        
        Rules:
        - If PROSPER.OPENFILE exists without PROSPER.START → prepend START
        - If PROSPER.START/OPENFILE exists without PROSPER.SHUTDOWN → append SHUTDOWN
        - Same logic for MBAL
        - GAP is exempt (orchestrator stays open)
        """
        result = list(commands)

        for app in ("PROSPER", "MBAL"):
            has_start = any(
                f"{app}.START" in (cmd.target or "")
                for cmd in result
                if cmd.method in ("DoCmd", "DoSlowCmd")
            )
            has_open = any(
                f"{app}.OPENFILE" in (cmd.target or "")
                for cmd in result
                if cmd.method in ("DoCmd", "DoSlowCmd")
            )
            has_shutdown = any(
                f"{app}.SHUTDOWN" in (cmd.target or "")
                for cmd in result
            )

            # If there's OPENFILE without START → prepend START
            if has_open and not has_start:
                result.insert(
                    0,
                    OpenServerCommand(method="DoCmd", target=f'{app}.START("")'),
                )

            # If there's START or OPENFILE without SHUTDOWN → append SHUTDOWN
            if (has_start or has_open) and not has_shutdown:
                result.append(
                    OpenServerCommand(method="DoCmd", target=f"{app}.SHUTDOWN()")
                )

        return result

    def generate_batch_wells(
        self,
        operation: str,
        well_names: list[str],
        prosper_files: dict[str, str],
        per_well_commands_fn: str,
        gap_model: str,
        description: Optional[str] = None,
    ) -> str:
        """Generate a script that processes wells one-by-one (1 PROSPER license).
        
        Pattern:
            GAP stays open
            For each well:
                PROSPER.START → PROSPER.OPENFILE(well) → process → PROSPER.SAVEFILE → PROSPER.SHUTDOWN
            
        This ensures only 1 PROSPER license is consumed at a time.
        
        Args:
            operation: Script operation name.
            well_names: List of well names to process.
            prosper_files: Mapping well_name → PROSPER file path.
            per_well_commands_fn: Name of the GAP function to call per well.
            gap_model: GAP model file path.
            description: Optional description.
            
        Returns:
            Complete Python script string.
        """
        lines: list[str] = []

        lines.append(f'"""PETEX OpenServer Script: {operation}')
        lines.append("")
        lines.append(f"Generated by PETEX MCP Server")
        lines.append(f"Timestamp: {datetime.now(timezone.utc).isoformat()}")
        lines.append("")
        lines.append("License optimization: processes wells SEQUENTIALLY.")
        lines.append("Only 1 PROSPER instance open at a time.")
        lines.append(f"Wells to process: {len(well_names)}")
        lines.append('"""')
        lines.append("")
        lines.append("from openserver import OpenServer")
        lines.append("import time")
        lines.append("")
        lines.append("with OpenServer() as c:")

        if description:
            lines.append(f"    # {description}")
            lines.append("")

        # Open GAP (stays open throughout)
        lines.append(f'    c.DoCmd("GAP.OPENFILE(\\"{gap_model}\\")")')
        lines.append(f"    time.sleep(2)")
        lines.append("")

        # Process each well sequentially
        for i, well_name in enumerate(well_names, 1):
            prosper_file = prosper_files.get(well_name, f"{well_name}.Out")
            lines.append(f"    # --- Well {i}/{len(well_names)}: {well_name} ---")
            lines.append(f'    c.DoCmd("PROSPER.START(\\"\\")")')
            lines.append(f"    time.sleep(5)")
            lines.append(f'    c.DoCmd("PROSPER.OPENFILE(\\"{prosper_file}\\")")')
            lines.append(f"    time.sleep(2)")
            lines.append(f'    c.DoGAPFunc("{per_well_commands_fn}(\\"{well_name}\\")")')
            lines.append(f"    time.sleep(10)")
            lines.append(f'    c.DoCmd("PROSPER.SAVEFILE(\\"{prosper_file}\\")")')
            lines.append(f"    time.sleep(1)")
            lines.append(f'    c.DoCmd("PROSPER.SHUTDOWN()")')
            lines.append(f"    time.sleep(2)")
            lines.append("")

        # Save GAP
        lines.append(f'    c.DoCmd("GAP.SAVEFILE(\\"{gap_model}\\")")')
        lines.append("")

        return "\n".join(lines) + "\n"

    def generate_serial_mbal(
        self,
        operation: str,
        mbal_files: list[str],
        per_tank_commands: list[list[OpenServerCommand]],
        description: Optional[str] = None,
    ) -> str:
        """Generate a script that processes MBAL tanks one-by-one (1 license).
        
        Pattern:
            For each tank:
                MBAL.START → MBAL.OPENFILE → process → MBAL.SAVEFILE → MBAL.SHUTDOWN
                
        Args:
            operation: Script operation name.
            mbal_files: List of MBAL file paths.
            per_tank_commands: Commands for each tank (parallel list).
            description: Optional description.
            
        Returns:
            Complete Python script string.
        """
        lines: list[str] = []

        lines.append(f'"""PETEX OpenServer Script: {operation}')
        lines.append("")
        lines.append(f"Generated by PETEX MCP Server")
        lines.append(f"Timestamp: {datetime.now(timezone.utc).isoformat()}")
        lines.append("")
        lines.append("License optimization: processes MBAL tanks SEQUENTIALLY.")
        lines.append("Only 1 MBAL instance open at a time.")
        lines.append(f"Tanks to process: {len(mbal_files)}")
        lines.append('"""')
        lines.append("")
        lines.append("from openserver import OpenServer")
        lines.append("import time")
        lines.append("")
        lines.append("with OpenServer() as c:")

        if description:
            lines.append(f"    # {description}")
            lines.append("")

        for i, (mbal_file, commands) in enumerate(
            zip(mbal_files, per_tank_commands), 1
        ):
            lines.append(f"    # --- Tank {i}/{len(mbal_files)}: {mbal_file} ---")
            lines.append(f'    c.DoCmd("MBAL.START(\\"\\")")')
            lines.append(f"    time.sleep(5)")
            lines.append(f'    c.DoSlowCmd("MBAL.OPENFILE=\\"{mbal_file}\\"")')
            lines.append(f"    time.sleep(2)")

            for cmd in commands:
                lines.append(f"    {self._build_command_line(cmd)}")

            lines.append(f'    c.DoCmd("MBAL.SaveFile(\\"{mbal_file}\\")")')
            lines.append(f"    time.sleep(1)")
            lines.append(f'    c.DoCmd("MBAL.SHUTDOWN()")')
            lines.append(f"    time.sleep(2)")
            lines.append("")

        return "\n".join(lines) + "\n"

    def generate_fragment(
        self,
        commands: list[OpenServerCommand],
        description: Optional[str] = None,
    ) -> str:
        """Generate a script fragment (no imports/connection) for incremental operations."""
        lines: list[str] = []

        if description:
            lines.append(f"    # --- {description} ---")

        for cmd in commands:
            lines.append(f"    {self._build_command_line(cmd)}")

        lines.append("")
        return "\n".join(lines) + "\n"

    def consolidate(self, operations: list[dict]) -> str:
        """Combine multiple operations into a single consolidated script.
        
        License optimization: the consolidated script ensures that:
        - PROSPER is started/shutdown for each well (never >1 open)
        - MBAL is started/shutdown for each tank (never >1 open)
        - GAP stays open throughout as orchestrator
        """
        lines: list[str] = []

        # Header
        lines.append('"""PETEX OpenServer Script: Consolidated Operations')
        lines.append("")
        lines.append("Generated by PETEX MCP Server")
        lines.append(f"Timestamp: {datetime.now(timezone.utc).isoformat()}")
        lines.append("")
        lines.append("License optimization: max 1 PROSPER + 1 MBAL active at a time.")
        lines.append('"""')
        lines.append("")
        lines.append("from openserver import OpenServer")
        lines.append("import time")
        lines.append("")
        lines.append("with OpenServer() as c:")

        if not operations:
            lines.append("    pass")
        else:
            for i, op in enumerate(operations, start=1):
                op_name = op.get("operation", f"Operation {i}")
                description = op.get("description")
                commands = op.get("commands", [])

                lines.append("")
                lines.append(f"    # --- Step {i}: {op_name} ---")
                if description:
                    lines.append(f"    # {description}")

                for cmd in commands:
                    lines.append(f"    {self._build_command_line(cmd)}")

        lines.append("")
        return "\n".join(lines) + "\n"

    def _build_command_line(self, command: OpenServerCommand) -> str:
        """Convert a single OpenServerCommand to a Python code line."""
        method = command.method
        target = command.target
        value = command.value

        if method == "DoSet":
            return f'c.DoSet("{target}", "{value}")'
        elif method == "DoGet":
            return f'result = c.DoGet("{target}")'
        elif method == "DoCmd":
            return f'c.DoCmd("{target}")'
        elif method == "DoSlowCmd":
            return f'c.DoSlowCmd("{target}")'
        else:
            return f'c.{method}("{target}")'
